version: '3.3'

services:
  custom_givenergy_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: custom_givenergy_api
    restart: always
    ports:
      - 5000:5000
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
      - PORT=5000
      - MAX_WORKERS=1